#!/bin/awk -f
# this awk script is used to calculate the weight percentage of identity from a file generated by blast3p.pl

BEGIN{FS=OFS="\t";n=0}
NR>1 && $7>=100 && $8>=100 && $9>=100{
	n++;
	for(i=1;i<=NF;i++){
		a[n,i]=$i;
	}
	len[1]+=$7;
	len[2]+=$8;
	len[3]+=$9;
}

END{
	len[1]/=n;
	len[2]/=n;
	len[3]/=n;
	for(i=1;i<=n;i++){
	if(a[i,1]){
		printf a[i,1];
		for(j=2;j<=NF;j++){
			printf "\t"a[i,j];
		}
		for(j=1;j<=3;j++){
			printf "\t"a[i,j+3]*a[i,j+6]/len[j];
		}
		print "";
	}
	}
}
1.	 Script getHomGap.pl

#!/usr/bin/perl

# this script is used for merging the blast results of ortholog proteins in 3 species 
# simply using this script:
# perl getHomGap.pl [blastFile1] [blastFile2] [blastFile3] [outFile]

open FILE1,"@ARGV[0]" or die;
open FILE2,"@ARGV[1]" or die;
open FILE3,"@ARGV[2]" or die;
open FILE4,">@ARGV[3]" or die;

# print the header first 
print FILE4 "query1\tquery2\tquery3\tPiden1-2\tPiden2-3\tPiden1-3\tleng1-2\tleng2-3\tleng1-3\tgap1-2\tgap2-3\tgap1-3\n";
while(<FILE1>){
	chomp;
	my @seq1=split /\t/;
	while(<FILE2>){
		chomp;
		my @seq2=split /\t/;
		if($seq1[1] eq $seq2[0] ){
			while(<FILE3>){
				chomp;
				my @seq3=split /\t/;
				if($seq3[0] eq $seq1[0] and $seq3[1] eq $seq2[1] ){
					print FILE4 "$seq1[0]\t$seq1[1]\t$seq2[1]\t$seq1[2]\t$seq2[2]\t$seq3[2]\t$seq1[3]\t$seq2[3]\t$seq3[3]\t$seq1[5]\t$seq2[5]\t$seq3[5]\n";
				}
			} 
			close FILE3;
			open FILE3,"@ARGV[2]" or die;
		}

	}
	close FILE2;
	open FILE2,"@ARGV[1]" or die;
}
close FILE1;
close FILE4;

