#!/bin/perl

#This script is used to calculate the overlap number and ratio from a original .clu file generated by Clustalo(version 1.2.0) which has only 3 proteins compared and the order must be most complex one to simple one.

#Check http://www.clustal.org for more information and updates.

#Simply using this script: 

#OverlapsCal.pl [clustaloFile]
#The result will be diplayed on your terminal directly.

open FILE,"@ARGV[0]" or die"the file @ARGV[0] is not exist.Please check out again."; 
#skip 3 lines
for($i=0;$i<3;$i++){    
	<FILE>;
}
#initialize variables
$seq1="";
$seq2="";
$seq3="";
$overlaps=0;
$variation1to2=0;
$variation2to3=0;
$variation1to3=0;
$v1=0;  #calculate the number of the only different various in sequence 1(/2/3).
$v2=0;
$v3=0;
$iden=0;
#read 3 sequences to 3 string variables.
while(<FILE>){
	chomp;
	my @line=split /\s+/;
	if($i%5==3){
		$seq1=$seq1.@line[1];
	}elsif($i%5==4){
		$seq2=$seq2.@line[1];
	}elsif($i%5==0){
		$seq3=$seq3.@line[1];
	}
	$i++;
}
close FILE;
#transform strings to arrays
@seq1=split //,$seq1;
@seq2=split //,$seq2;
@seq3=split //,$seq3;

#calulation block
$len=length($seq1);
for($i=0;$i<$len;$i++){
	if(@seq1[$i] ne @seq2[$i] ) {$variation1to2++;if(@seq2[$i] eq @seq3[$i]){$v1++}};
	if(@seq1[$i] ne @seq3[$i] ) {$variation1to3++;if(@seq1[$i] eq @seq2[$i]){$v3++}};
	if(@seq2[$i] ne @seq3[$i]){
		$variation2to3++;
		if(@seq1[$i] eq @seq3[$i]){$v2++}
		if(@seq1[$i] ne @seq2[$i] and @seq1[$i] ne @seq3[$i]){
			$overlaps++;
		}
	}
}

$overlapRatio = $overlaps/$variation1to2*100;
$ident1to2 = 100-$variation1to2/$len*100;
$ident1to3 = 100-$variation1to3/$len*100;
$ident2to3 = 100-$variation2to3/$len*100;

#Put out the result
print "******@ARGV[0]******\nSequence-lenth: ".$len."\nOverlaps: ".$overlaps."\nvariation1to2: ".$variation1to2."\nOverlap-ratio: ";
printf "%3.1f\%\n%s%3.1f\%\t%s%3.1f\%\t%s%3.1f\%\n",$overlapRatio,"Pident1to2: ",$ident1to2,"Pident1to3: ",$ident1to3,"Pident2to3: ",$ident2to3;
print "var1:".$v1."\tvar2:".$v2."\tvar3:".$v3."\n";
print "*****************************\n";

